//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voda.VodokanalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VodokanalService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginEx(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByCookies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginByCookies(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SignOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuthenticated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsAuthenticated();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByGoogleId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginByGoogleId(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Execute(string calcId, string args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteEx(string calcId, string args, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteWithTimeout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteWithTimeout(string calcId, string args, string ticket, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateSession(string ticket, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangePassword(string login, string oldPassword, string newPassword, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object IsEnabled();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : voda.VodokanalService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<voda.VodokanalService.WebServiceSoap>, voda.VodokanalService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public string LoginEx(string login, string password) {
            return base.Channel.LoginEx(login, password);
        }
        
        public string LoginByCookies(string value) {
            return base.Channel.LoginByCookies(value);
        }
        
        public void SignOut() {
            base.Channel.SignOut();
        }
        
        public bool IsAuthenticated() {
            return base.Channel.IsAuthenticated();
        }
        
        public string LoginByGoogleId(string token) {
            return base.Channel.LoginByGoogleId(token);
        }
        
        public string Execute(string calcId, string args) {
            return base.Channel.Execute(calcId, args);
        }
        
        public string ExecuteEx(string calcId, string args, string ticket) {
            return base.Channel.ExecuteEx(calcId, args, ticket);
        }
        
        public string ExecuteWithTimeout(string calcId, string args, string ticket, int timeout) {
            return base.Channel.ExecuteWithTimeout(calcId, args, ticket, timeout);
        }
        
        public void UpdateSession(string ticket, string sessionId) {
            base.Channel.UpdateSession(ticket, sessionId);
        }
        
        public string ChangePassword(string login, string oldPassword, string newPassword, string ticket) {
            return base.Channel.ChangePassword(login, oldPassword, newPassword, ticket);
        }
        
        public object IsEnabled() {
            return base.Channel.IsEnabled();
        }
    }
}
